spring.application.name=demo-spring

# --- Datasource MySQL ---
# Valeur par défaut = MySQL local ; overridable par SPRING_DATASOURCE_URL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/service_client?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&useUnicode=true&characterEncoding=utf8}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}

# --- Pool Hikari (optionnel mais conseillé) ---
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=600000
spring.datasource.hikari.connection-timeout=30000

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# --- JWT ---
jwt.secret=${JWT_SECRET:VGhpcy1pcy1hLWxvbmcsc3Ryb25nLC1iYXNlNjQtc2VjcmV0LWtleS1mb3ItSFMtMjU2IQ==}
jwt.expiration=${JWT_EXPIRATION:3600000}

# --- Port HTTP (8080 par défaut) ---
server.port=${SERVER_PORT:8080}

management.server.port=8081
management.endpoints.web.exposure.include=health,info,prometheus,metrics
management.endpoint.health.probes.enabled=true
# metrics à http://localhost:8081/actuator/prometheus

# (prod conseillée)
# spring.jpa.open-in-view=false

# management.endpoints.web.exposure.include=health,info
# management.endpoint.health.probes.enabled=true
# management.endpoints.web.base-path=/actuator   # (par défaut déjà /actuator)

### Utilisation de RabbitMQ
spring.rabbitmq.host=rabbitmq
spring.rabbitmq.port=5672
spring.rabbitmq.username=guest
spring.rabbitmq.password=guest
# JSON automatique
spring.rabbitmq.template.mandatory=true

